"""add disputed flag to cases

Revision ID: 05280d324a02
Revises: eff73bc63ca6
Create Date: 2026-08-23 13:09:42.479127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05280d324a02'
down_revision: Union[str, None] = 'eff73bc63ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; Boolean's Python-side default
    # alone only applies to new inserts, not the NOT NULL backfill here.
    op.add_column('cases', sa.Column('disputed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('cases', 'disputed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'disputed')
    # ### end Alembic commands ###
