"""add merchants, tickets, case merchant_id and next_action_at

Revision ID: 171350621f1a
Revises: 7d7c260eac6c
Create Date: 2026-08-23 16:30:32.227898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171350621f1a'
down_revision: Union[str, None] = '7d7c260eac6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_tickets_merchant_id'), 'tickets', ['merchant_id'], unique=False)
    op.add_column('cases', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_cases_merchant_id'), 'cases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_cases_next_action_at'), 'cases', ['next_action_at'], unique=False)
    op.create_foreign_key(None, 'cases', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_next_action_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_merchant_id'), table_name='cases')
    op.drop_column('cases', 'next_action_at')
    op.drop_column('cases', 'merchant_id')
    op.drop_index(op.f('ix_tickets_merchant_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('merchants')
    # ### end Alembic commands ###
