"""add batch_id to cases

Revision ID: 7d7c260eac6c
Revises: bbfc977fd9d1
Create Date: 2026-08-23 13:56:54.909528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7c260eac6c'
down_revision: Union[str, None] = 'bbfc977fd9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cases_batch_id'), 'cases', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_batch_id'), table_name='cases')
    op.drop_column('cases', 'batch_id')
    # ### end Alembic commands ###
