"""SQLAlchemy models: Case, Customer, Attempt, AuditEvent (PRD §6).

`root_cause`, `action`, and `event_type` are stored as plain strings rather
than native Postgres enums. They're validated against the Python enums/lists
in `app/constants.py` at the application layer — this avoids a migration
every time Phase 6 (receivables) or later work adds a new root cause or
action to the bounded action space.
"""
import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, Numeric, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base


class Merchant(Base):
    """A tenant. No auth in this build (deliberately, to keep judge/demo
    access frictionless) - tenancy is enforced by scoping every query to a
    merchant_id, not by a login wall.
    """

    __tablename__ = "merchants"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(100))
    slug: Mapped[str] = mapped_column(String(50), unique=True)

    cases: Mapped[list["Case"]] = relationship(back_populates="merchant")


class Customer(Base):
    __tablename__ = "customers"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    dnd_registered: Mapped[bool] = mapped_column(default=False)
    responsiveness_profile: Mapped[str] = mapped_column(String(20))
    preferred_channel: Mapped[str] = mapped_column(String(20))
    card_on_file_status: Mapped[str] = mapped_column(String(30))

    cases: Mapped[list["Case"]] = relationship(back_populates="customer")


class Case(Base):
    __tablename__ = "cases"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    type: Mapped[str] = mapped_column(String(20))
    customer_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("customers.id"))
    amount: Mapped[float] = mapped_column(Numeric(12, 2))
    currency: Mapped[str] = mapped_column(String(3), default="INR")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="open")
    raw_failure_reason: Mapped[str | None] = mapped_column(String(500), nullable=True)
    root_cause: Mapped[str | None] = mapped_column(String(50), nullable=True)
    outcome: Mapped[str] = mapped_column(String(20), default="pending")
    recovered_amount: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    disputed: Mapped[bool] = mapped_column(default=False)
    # Groups cases generated by one POST /batches/run or seed script
    # invocation, so a batch's rollup (app/audit/rollup.py) can be scoped
    # to just its own cases instead of the whole cumulative dev DB.
    # Nullable because cases seeded before Phase 7 have no batch_id.
    batch_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True, index=True)
    # Tenant scoping. Nullable for the same reason batch_id is - cases
    # seeded before multi-tenancy landed have no merchant.
    merchant_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("merchants.id"), nullable=True, index=True)
    # When set, this case is waiting for a deferred follow-up round rather
    # than having been driven to a terminal state in one pass - see
    # app/execution/runner.py's non-instant mode and POST /jobs/run-due.
    next_action_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, index=True)

    merchant: Mapped["Merchant | None"] = relationship(back_populates="cases")
    customer: Mapped["Customer"] = relationship(back_populates="cases")
    attempts: Mapped[list["Attempt"]] = relationship(back_populates="case", order_by="Attempt.timestamp")
    audit_events: Mapped[list["AuditEvent"]] = relationship(back_populates="case", order_by="AuditEvent.timestamp")


class Attempt(Base):
    __tablename__ = "attempts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    case_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("cases.id"))
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    channel: Mapped[str] = mapped_column(String(30))
    action: Mapped[str] = mapped_column(String(30))
    compliance_check: Mapped[dict] = mapped_column(JSONB)
    outcome: Mapped[str] = mapped_column(String(20))
    promise_to_pay_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    transcript: Mapped[str | None] = mapped_column(String, nullable=True)

    case: Mapped["Case"] = relationship(back_populates="attempts")


class AuditEvent(Base):
    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    case_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("cases.id"))
    attempt_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("attempts.id"), nullable=True)
    # Server-side clock_timestamp() (not Python-side datetime.utcnow()):
    # several AuditEvents are routinely created within the same flush
    # (e.g. action_proposed + compliance_check back to back), and
    # datetime.utcnow()'s resolution on this system was observed producing
    # byte-identical timestamps for them, which breaks chronological
    # ordering. clock_timestamp() is evaluated per row by Postgres itself.
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.clock_timestamp())
    event_type: Mapped[str] = mapped_column(String(30))
    actor: Mapped[str] = mapped_column(String(10))
    payload: Mapped[dict] = mapped_column(JSONB)

    case: Mapped["Case"] = relationship(back_populates="audit_events")


class Ticket(Base):
    """In-house mock of a support/collections tool. Auto-created whenever
    a case is escalated to a human (app/execution/runner.py), so
    escalate_human has somewhere real to land instead of being a dead-end
    status - this is the "fake support tool" for the demo, not an
    integration with a real external ticketing product.
    """

    __tablename__ = "tickets"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    case_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("cases.id"), unique=True)
    merchant_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("merchants.id"), nullable=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.clock_timestamp())
    subject: Mapped[str] = mapped_column(String(200))
    priority: Mapped[str] = mapped_column(String(10), default="normal")  # low | normal | high | urgent
    status: Mapped[str] = mapped_column(String(20), default="open")  # open | in_progress | resolved
    assignee: Mapped[str] = mapped_column(String(50), default="Unassigned")
    reason: Mapped[str] = mapped_column(String(500))

    case: Mapped["Case"] = relationship()
